version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-code-reviewer-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai_code_reviewer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-code-reviewer-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-code-reviewer-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      DATABASE_URL: postgresql://admin:password123@postgres:5432/ai_code_reviewer
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
    networks:
      - ai-code-reviewer-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: ai-code-reviewer-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ai-code-reviewer-network

volumes:
  postgres_data:

networks:
  ai-code-reviewer-network:
    driver: bridge